[2021-07-19 09:18:17,885] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:18:18,047] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:18:18,047] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:18:18,047] {taskinstance.py:1088} INFO - Starting attempt 6 of 6
[2021-07-19 09:18:18,047] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:18:18,401] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:18:18,404] {standard_task_runner.py:52} INFO - Started process 3279 to run task
[2021-07-19 09:18:18,407] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'insert_data_to_db', '2021-07-18T07:54:25.449895+00:00', '--job-id', '115', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmp0upe_tsi', '--error-file', '/tmp/tmpxzob8_t0']
[2021-07-19 09:18:18,407] {standard_task_runner.py:77} INFO - Job 115: Subtask insert_data_to_db
[2021-07-19 09:18:19,625] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.insert_data_to_db 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 09:18:21,143] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=insert_data_to_db
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:18:22,739] {python.py:151} INFO - Done. Returned value was: None
[2021-07-19 09:18:23,027] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=insert_data_to_db, execution_date=20210718T075425, start_date=20210719T091817, end_date=20210719T091823
[2021-07-19 09:18:23,753] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 09:18:24,330] {local_task_job.py:151} INFO - Task exited with return code 0
