[2021-07-20 07:18:11,933] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 07:18:12,332] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 07:18:12,334] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 07:18:12,334] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-20 07:18:12,334] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 07:18:12,469] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_data> on 2021-07-19T00:00:00+00:00
[2021-07-20 07:18:12,471] {standard_task_runner.py:52} INFO - Started process 31724 to run task
[2021-07-20 07:18:12,474] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'save_data', '2021-07-19T00:00:00+00:00', '--job-id', '151', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmprbs5diz9', '--error-file', '/tmp/tmp8zdxr31j']
[2021-07-20 07:18:12,474] {standard_task_runner.py:77} INFO - Job 151: Subtask save_data
[2021-07-20 07:18:13,725] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.save_data 2021-07-19T00:00:00+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-20 07:18:15,352] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=save_data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 07:18:15,958] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 07:18:16,256] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=save_data, execution_date=20210719T000000, start_date=20210720T071811, end_date=20210720T071816
[2021-07-20 07:18:17,106] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 07:18:17,142] {local_task_job.py:151} INFO - Task exited with return code 0
