[2021-07-18 07:58:27,947] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-18 07:58:28,102] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-18 07:58:28,102] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 07:58:28,102] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 07:58:28,102] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 07:58:28,450] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_6> on 2021-07-18T07:54:25.449895+00:00
[2021-07-18 07:58:28,454] {standard_task_runner.py:52} INFO - Started process 7183 to run task
[2021-07-18 07:58:28,460] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'task_6', '2021-07-18T07:54:25.449895+00:00', '--job-id', '68', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpwd5dj774', '--error-file', '/tmp/tmp521jpf3m']
[2021-07-18 07:58:28,461] {standard_task_runner.py:77} INFO - Job 68: Subtask task_6
[2021-07-18 07:58:29,673] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-18 07:58:31,217] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=task_6
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-18 07:58:31,218] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 07:58:31,219] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-18 07:58:31,227] {subprocess.py:75} INFO - Output:
[2021-07-18 07:58:34,229] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-18 07:58:35,104] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=task_6, execution_date=20210718T075425, start_date=20210718T075827, end_date=20210718T075835
[2021-07-18 07:58:35,783] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-18 07:58:35,802] {local_task_job.py:151} INFO - Task exited with return code 0
