[2021-07-18 08:21:18,008] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-18 08:21:18,169] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-18 08:21:18,169] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 08:21:18,169] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-18 08:21:18,169] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 08:21:18,531] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_6> on 2021-07-18T07:54:25.449895+00:00
[2021-07-18 08:21:18,535] {standard_task_runner.py:52} INFO - Started process 8149 to run task
[2021-07-18 08:21:18,541] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'task_6', '2021-07-18T07:54:25.449895+00:00', '--job-id', '77', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmp4r4ua9mi', '--error-file', '/tmp/tmpqn5235jn']
[2021-07-18 08:21:18,542] {standard_task_runner.py:77} INFO - Job 77: Subtask task_6
[2021-07-18 08:21:19,792] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.task_6 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-18 08:21:21,260] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=task_6
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-18 08:21:21,261] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 08:21:21,261] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-18 08:21:21,270] {subprocess.py:75} INFO - Output:
[2021-07-18 08:21:24,272] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-18 08:21:25,129] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=task_6, execution_date=20210718T075425, start_date=20210718T082118, end_date=20210718T082125
[2021-07-18 08:21:25,795] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-18 08:21:25,818] {local_task_job.py:151} INFO - Task exited with return code 0
