[2021-07-19 08:53:04,987] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_4 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:53:05,186] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_4 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:53:05,186] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:53:05,186] {taskinstance.py:1088} INFO - Starting attempt 4 of 4
[2021-07-19 08:53:05,186] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:53:05,539] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:53:05,542] {standard_task_runner.py:52} INFO - Started process 2108 to run task
[2021-07-19 08:53:05,545] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'task_4', '2021-07-18T07:54:25.449895+00:00', '--job-id', '98', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmphfqk5212', '--error-file', '/tmp/tmpmcz_g57g']
[2021-07-19 08:53:05,545] {standard_task_runner.py:77} INFO - Job 98: Subtask task_4
[2021-07-19 08:53:06,770] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.task_4 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 08:53:08,266] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:53:08,267] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 08:53:08,267] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 08:53:08,273] {subprocess.py:75} INFO - Output:
[2021-07-19 08:53:11,276] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 08:53:12,148] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=task_4, execution_date=20210718T075425, start_date=20210719T085304, end_date=20210719T085312
[2021-07-19 08:53:12,861] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 08:53:12,883] {local_task_job.py:151} INFO - Task exited with return code 0
