[2021-07-19 09:53:01,161] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.qc_check 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:53:01,319] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.qc_check 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 09:53:01,319] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:53:01,320] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-19 09:53:01,320] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 09:53:01,695] {taskinstance.py:1107} INFO - Executing <Task(BranchPythonOperator): qc_check> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:53:01,698] {standard_task_runner.py:52} INFO - Started process 5075 to run task
[2021-07-19 09:53:01,701] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'qc_check', '2021-07-18T07:54:25.449895+00:00', '--job-id', '131', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmp3yipw_da', '--error-file', '/tmp/tmp7yufryke']
[2021-07-19 09:53:01,701] {standard_task_runner.py:77} INFO - Job 131: Subtask qc_check
[2021-07-19 09:53:02,942] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.qc_check 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 09:53:04,461] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=qc_check
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 09:53:04,465] {python.py:151} INFO - Done. Returned value was: upload_to_haft
[2021-07-19 09:53:04,465] {skipmixin.py:124} INFO - Following branch upload_to_haft
[2021-07-19 09:53:04,750] {skipmixin.py:155} INFO - Skipping tasks ['send_qc_failed_alert']
[2021-07-19 09:53:06,460] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=qc_check, execution_date=20210718T075425, start_date=20210719T095301, end_date=20210719T095306
[2021-07-19 09:53:07,199] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-19 09:53:07,610] {local_task_job.py:151} INFO - Task exited with return code 0
