[2021-07-19 08:38:39,259] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_1 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:38:39,425] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.task_1 2021-07-18T07:54:25.449895+00:00 [queued]>
[2021-07-19 08:38:39,425] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:38:39,425] {taskinstance.py:1088} INFO - Starting attempt 3 of 3
[2021-07-19 08:38:39,425] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 08:38:39,778] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_1> on 2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:38:39,780] {standard_task_runner.py:52} INFO - Started process 1536 to run task
[2021-07-19 08:38:39,783] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'task_1', '2021-07-18T07:54:25.449895+00:00', '--job-id', '83', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmp9dslxvlt', '--error-file', '/tmp/tmps8kjgo3w']
[2021-07-19 08:38:39,784] {standard_task_runner.py:77} INFO - Job 83: Subtask task_1
[2021-07-19 08:38:41,000] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.task_1 2021-07-18T07:54:25.449895+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-19 08:38:42,526] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T07:54:25.449895+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T07:54:25.449895+00:00
[2021-07-19 08:38:42,527] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 08:38:42,527] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 08:38:42,533] {subprocess.py:75} INFO - Output:
[2021-07-19 08:38:45,537] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 08:38:46,452] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=task_1, execution_date=20210718T075425, start_date=20210719T083839, end_date=20210719T083846
[2021-07-19 08:38:47,191] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-07-19 08:38:47,209] {local_task_job.py:151} INFO - Task exited with return code 0
