[2021-07-23 12:11:10,669] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-22T00:00:00+00:00 [queued]>
[2021-07-23 12:11:11,047] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: autobot.save_data 2021-07-22T00:00:00+00:00 [queued]>
[2021-07-23 12:11:11,048] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:11:11,048] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-23 12:11:11,048] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-23 12:11:11,173] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): save_data> on 2021-07-22T00:00:00+00:00
[2021-07-23 12:11:11,177] {standard_task_runner.py:52} INFO - Started process 884 to run task
[2021-07-23 12:11:11,183] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'autobot', 'save_data', '2021-07-22T00:00:00+00:00', '--job-id', '165', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/AutoBot.py', '--cfg-path', '/tmp/tmpuc0v3nbj', '--error-file', '/tmp/tmp3_bg6tm0']
[2021-07-23 12:11:11,184] {standard_task_runner.py:77} INFO - Job 165: Subtask save_data
[2021-07-23 12:11:12,430] {logging_mixin.py:104} INFO - Running <TaskInstance: autobot.save_data 2021-07-22T00:00:00+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-23 12:11:13,965] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=autobot
AIRFLOW_CTX_TASK_ID=save_data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-22T00:00:00+00:00
[2021-07-23 12:11:14,517] {python.py:151} INFO - Done. Returned value was: None
[2021-07-23 12:11:14,809] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=autobot, task_id=save_data, execution_date=20210722T000000, start_date=20210723T121110, end_date=20210723T121114
[2021-07-23 12:11:15,537] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-23 12:11:15,575] {local_task_job.py:151} INFO - Task exited with return code 0
