[2021-07-15 09:15:35,620] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.Storing_user 2021-07-15T09:11:10.481157+00:00 [queued]>
[2021-07-15 09:15:35,626] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.Storing_user 2021-07-15T09:11:10.481157+00:00 [queued]>
[2021-07-15 09:15:35,626] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 09:15:35,626] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-15 09:15:35,626] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 09:15:35,638] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): Storing_user> on 2021-07-15T09:11:10.481157+00:00
[2021-07-15 09:15:35,641] {standard_task_runner.py:52} INFO - Started process 3837 to run task
[2021-07-15 09:15:35,647] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'Storing_user', '2021-07-15T09:11:10.481157+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmph2g1_f8e', '--error-file', '/tmp/tmpgnt7sq4b']
[2021-07-15 09:15:35,648] {standard_task_runner.py:77} INFO - Job 30: Subtask Storing_user
[2021-07-15 09:15:35,680] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.Storing_user 2021-07-15T09:11:10.481157+00:00 [running]> on host apache-airflow.us-central1-a.c.eminent-it-info.internal
[2021-07-15 09:15:35,719] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=Storing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-07-15T09:11:10.481157+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-15T09:11:10.481157+00:00
[2021-07-15 09:15:35,721] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/karuturihemanth/airflow/dags/user_processing.py", line 20, in _read_the_file
    df = pd.read_csv('processed_user.csv')
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/karuturihemanth/airflow_env/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'processed_user.csv'
[2021-07-15 09:15:35,732] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=user_processing, task_id=Storing_user, execution_date=20210715T091110, start_date=20210715T091535, end_date=20210715T091535
[2021-07-15 09:15:35,778] {local_task_job.py:151} INFO - Task exited with return code 1
